name: Setup development environment 
description: Setup runner to be able to use deno. 

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
  - uses: denoland/setup-deno@v1
    with:
      deno-version: v1.x